{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opssightai-database
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "opssightai.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
    protocol: TCP
    name: postgresql
  selector:
    {{- include "opssightai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  clusterIP: None
{{- end }}
