apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opssightai-ingress-ssl
  namespace: opssightai
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "opssightai-ip"
    networking.gke.io/managed-certificates: "opssightai-ssl-cert"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - host: opssightai.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: opssightai-backend
            port:
              number: 4000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opssightai-frontend
            port:
              number: 80
  - host: www.opssightai.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: opssightai-backend
            port:
              number: 4000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opssightai-frontend
            port:
              number: 80
